class com.adobe.creativesdk.foundation.internal.auth.d$a extends java.lang.Object
{
    final com.adobe.creativesdk.foundation.internal.auth.d a;
    private java.security.PrivateKey b;
    private java.security.PublicKey c;
    private boolean d;

    public void <init>(com.adobe.creativesdk.foundation.internal.auth.d)
    {
        com.adobe.creativesdk.foundation.internal.auth.d$a $r0;
        com.adobe.creativesdk.foundation.internal.auth.d $r1;
        boolean $z0;
        int varReplacer6218;

        nop;

        $r0 := @this: com.adobe.creativesdk.foundation.internal.auth.d$a;

        $r1 := @parameter0: com.adobe.creativesdk.foundation.internal.auth.d;

        $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: com.adobe.creativesdk.foundation.internal.auth.d a> = $r1;

        specialinvoke $r0.<java.lang.Object: void <init>()>();

        varReplacer6218 = 0;

        $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: boolean d> = varReplacer6218;

        $z0 = $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: boolean d>;

        if $z0 != 0 goto label1;

     label1:
        return;
    }

    private javax.crypto.Cipher a()
    {
        com.adobe.creativesdk.foundation.internal.auth.d$a $r0;
        javax.crypto.Cipher $r1;
        java.lang.Exception $r2;
        java.lang.IllegalArgumentException $r3;
        java.lang.String varReplacer7113, varReplacer7114, varReplacer7115;

        nop;

        $r0 := @this: com.adobe.creativesdk.foundation.internal.auth.d$a;

     label1:
        varReplacer7113 = "RSA/ECB/PKCS1Padding";

        varReplacer7114 = "AndroidOpenSSL";

        $r1 = staticinvoke <javax.crypto.Cipher: javax.crypto.Cipher getInstance(java.lang.String,java.lang.String)>(varReplacer7113, varReplacer7114);

     label2:
        return $r1;

     label3:
        $r2 := @caughtexception;

        $r3 = new java.lang.IllegalArgumentException;

        varReplacer7115 = "Auth Foundation : Auth AESKeyMgr : Failed to create Cipher";

        specialinvoke $r3.<java.lang.IllegalArgumentException: void <init>(java.lang.String,java.lang.Throwable)>(varReplacer7115, $r2);

        throw $r3;

        catch java.lang.Exception from label1 to label2 with label3;
    }

    private byte[] c(byte[])
    {
        com.adobe.creativesdk.foundation.internal.auth.d$a $r0;
        byte[] $r1;
        javax.crypto.Cipher $r2;
        java.security.PublicKey $r3;
        java.lang.Exception $r4;
        com.adobe.creativesdk.foundation.internal.utils.logging.Level $r5;
        java.lang.String $r6, $r7, varReplacer7116;
        java.lang.IllegalArgumentException $r8;
        int varReplacer7117;

        nop;

        $r0 := @this: com.adobe.creativesdk.foundation.internal.auth.d$a;

        $r1 := @parameter0: byte[];

        $r2 = specialinvoke $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: javax.crypto.Cipher a()>();

     label1:
        $r3 = $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: java.security.PublicKey c>;

        varReplacer7117 = 1;

        virtualinvoke $r2.<javax.crypto.Cipher: void init(int,java.security.Key)>(varReplacer7117, $r3);

        $r1 = virtualinvoke $r2.<javax.crypto.Cipher: byte[] doFinal(byte[])>($r1);

     label2:
        return $r1;

     label3:
        $r4 := @caughtexception;

        $r5 = <com.adobe.creativesdk.foundation.internal.utils.logging.Level: com.adobe.creativesdk.foundation.internal.utils.logging.Level c>;

        $r6 = staticinvoke <com.adobe.creativesdk.foundation.internal.auth.d: java.lang.String e()>();

        $r7 = virtualinvoke $r4.<java.lang.Exception: java.lang.String getMessage()>();

        staticinvoke <com.adobe.creativesdk.foundation.internal.utils.logging.a: void a(com.adobe.creativesdk.foundation.internal.utils.logging.Level,java.lang.String,java.lang.String,java.lang.Throwable)>($r5, $r6, $r7, $r4);

        $r8 = new java.lang.IllegalArgumentException;

        varReplacer7116 = "Auth Foundation : Auth AESKeyMgr : Failed to encrypt using public key";

        specialinvoke $r8.<java.lang.IllegalArgumentException: void <init>(java.lang.String,java.lang.Throwable)>(varReplacer7116, $r4);

        throw $r8;

        catch java.lang.Exception from label1 to label2 with label3;
    }

    private byte[] d(byte[])
    {
        com.adobe.creativesdk.foundation.internal.auth.d$a $r0;
        byte[] $r1;
        javax.crypto.Cipher $r2;
        java.security.PrivateKey $r3;
        java.lang.Exception $r4;
        com.adobe.creativesdk.foundation.internal.utils.logging.Level $r5;
        java.lang.String $r6, $r7, varReplacer7111;
        java.lang.IllegalArgumentException $r8;
        int varReplacer7112;

        nop;

        $r0 := @this: com.adobe.creativesdk.foundation.internal.auth.d$a;

        $r1 := @parameter0: byte[];

        $r2 = specialinvoke $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: javax.crypto.Cipher a()>();

     label1:
        $r3 = $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: java.security.PrivateKey b>;

        varReplacer7112 = 2;

        virtualinvoke $r2.<javax.crypto.Cipher: void init(int,java.security.Key)>(varReplacer7112, $r3);

        $r1 = virtualinvoke $r2.<javax.crypto.Cipher: byte[] doFinal(byte[])>($r1);

     label2:
        return $r1;

     label3:
        $r4 := @caughtexception;

        $r5 = <com.adobe.creativesdk.foundation.internal.utils.logging.Level: com.adobe.creativesdk.foundation.internal.utils.logging.Level c>;

        $r6 = staticinvoke <com.adobe.creativesdk.foundation.internal.auth.d: java.lang.String e()>();

        $r7 = virtualinvoke $r4.<java.lang.Exception: java.lang.String getMessage()>();

        staticinvoke <com.adobe.creativesdk.foundation.internal.utils.logging.a: void a(com.adobe.creativesdk.foundation.internal.utils.logging.Level,java.lang.String,java.lang.String,java.lang.Throwable)>($r5, $r6, $r7, $r4);

        $r8 = new java.lang.IllegalArgumentException;

        varReplacer7111 = "Auth Foundation : Auth AESKeyMgr : Failed to decyrpt using private key";

        specialinvoke $r8.<java.lang.IllegalArgumentException: void <init>(java.lang.String,java.lang.Throwable)>(varReplacer7111, $r4);

        throw $r8;

        catch java.lang.Exception from label1 to label2 with label3;
    }

    public byte[] a(byte[])
    {
        com.adobe.creativesdk.foundation.internal.auth.d$a $r0;
        boolean $z0;
        byte[] $r1;

        nop;

        $r0 := @this: com.adobe.creativesdk.foundation.internal.auth.d$a;

        $r1 := @parameter0: byte[];

        $z0 = $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: boolean d>;

        if $z0 != 0 goto label1;

        return $r1;

     label1:
        $r1 = specialinvoke $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: byte[] c(byte[])>($r1);

        return $r1;
    }

    public byte[] b(byte[])
    {
        com.adobe.creativesdk.foundation.internal.auth.d$a $r0;
        boolean $z0;
        byte[] $r1;

        nop;

        $r0 := @this: com.adobe.creativesdk.foundation.internal.auth.d$a;

        $r1 := @parameter0: byte[];

        $z0 = $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: boolean d>;

        if $z0 != 0 goto label1;

        return $r1;

     label1:
        $r1 = specialinvoke $r0.<com.adobe.creativesdk.foundation.internal.auth.d$a: byte[] d(byte[])>($r1);

        return $r1;
    }
}
